### ISSUE TITLE
i can't run this project properly plz, tell.

### ISSUE THREAD

**Issue by bharatpathak894** [Artaghal/banglore-home-price-prediction-model#1]
i have copied as it is but cant run
![Screenshot (13)](https://user-images.githubusercontent.com/106964297/186497138-6a4cb648-ba18-4fa4-b367-ca578ef070d7.png)

**Comment by wasimkhana** [comment]
Hey Bharatpathak,
Following is a link to the tutorials to understand and resolve your issue;
[UI tutorial link](https://www.youtube.com/watch?v=rD2xumR98w8&list=PLeo1K3hjS3uu7clOTtwsp94PcHbzqpAdg&index=7)
